#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#
#springdoc:
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  swagger-ui:
#    path: /swagger.html
#    disable-swagger-default-url: true